version = 0.1
[default.deploy.parameters]
stack_name = "wts-chatbot"
resolve_s3 = true
s3_prefix = "wts-chatbot"
region = "ap-southeast-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
